CREATE DATABASE ASSIGNMENT;
 USE ASSIGNMENT;

CREATE TABLE EMPLOYEE (
SSN VARCHAR(20), 
FNAME VARCHAR(20),
 LNAME VARCHAR(20),
 ADDRESS VARCHAR(20), 
 SEX CHAR(1),
SALARY INTEGER
);

INSERT INTO EMPLOYEE (SSN, FNAME, LNAME, ADDRESS, SEX, SALARY) VALUES
('123-45-6789', 'John', 'Doe', '123 Elm St', 'M', 60000),
('987-65-4321', 'Jane', 'Smith', '456 Maple St', 'F', 75000),
('555-55-5555', 'Jim', 'Beam', '789 Oak St', 'M', 55000),
('222-33-4444', 'Jake', 'Blues', '321 Pine St', 'M', 70000);

CREATE TABLE EMPLOYEE2 (
SSN VARCHAR(20),
 FNAME VARCHAR(20),
 LNAME VARCHAR(20),
 ADDRESS VARCHAR(20), 
 SEX CHAR(1),
SALARY INTEGER
);

INSERT INTO EMPLOYEE2 (SSN, FNAME, LNAME, ADDRESS, SEX, SALARY) VALUES
('987-65-4321', 'Jane', 'Smith', '456 Maple St', 'F', 75000),
('555-55-5555', 'Jim', 'Beam', '789 Oak St', 'M', 55000);


CREATE TABLE DEPARTMENT (
DNUMBER INT, 
DNAME VARCHAR(20)
);

INSERT INTO DEPARTMENT (DNUMBER, DNAME) VALUES (1, 'HR'),
(2, 'Engineering');

SELECT * FROM EMPLOYEE WHERE SALARY > 50000; -- select , proejct

SELECT FNAME, LNAME FROM EMPLOYEE 
INTERSECT 
SELECT FNAME, LNAME FROM EMPLOYEE2; 

SELECT * FROM EMPLOYEE
INTERSECT
SELECT * FROM EMPLOYEE2; -- intersection

SELECT * FROM EMPLOYEE
EXCEPT
SELECT * FROM EMPLOYEE2; -- minus

SELECT * FROM EMPLOYEE, DEPARTMENT; -- cartesion

SELECT * FROM EMPLOYEE
UNION
SELECT * FROM EMPLOYEE2;

SELECT FNAME,LNAME, DNAME FROM EMPLOYEE, DEPARTMENT;  -- cartesion


