CREATE DATABASE DB; 
USE DB;
CREATE TABLE EMP (

EMPNO INT CHECK (EMPNO > 100), ENAME VARCHAR(20) NOT NULL, JOB VARCHAR(10) NOT NULL, DEPTNO INT UNIQUE,
SAL DECIMAL(7,2), PRIMARY KEY (EMPNO) );

-- Valid insert

INSERT INTO EMP (EMPNO, ENAME, JOB, DEPTNO, SAL) VALUES (101, 'Alice', 'Manager', 10, 5000.00);

-- Invalid insert (EMPNO <= 100)

INSERT INTO EMP (EMPNO, ENAME, JOB, DEPTNO, SAL) VALUES (100, 'Bob', 'Clerk', 20, 3000.00);

-- Valid insert (NULL ENAME)

INSERT INTO EMP (EMPNO, ENAME, JOB, DEPTNO, SAL) VALUES (103, 'Abhi', 'Clerk', 30, 2500.00);

select * from EMP;

UPDATE EMP
SET SAL = 5500.00
WHERE EMPNO = 101;

